-- Install Marvel/hero costumes generated by costume-tools/build_marvel_costumes.py
SET NAMES utf8mb4;
START TRANSACTION;

DELETE FROM item_shop_option WHERE item_shop_id IN (SELECT id FROM item_shop WHERE tab_id = 1120 AND temp_id IN (2080));
DELETE FROM item_shop WHERE tab_id = 1120 AND temp_id IN (2080);
DELETE FROM item_default_option WHERE item_template_id IN (2080);
DELETE FROM head_avatar WHERE head_id IN (2189, 2190, 2191);
DELETE FROM item_template WHERE id IN (2080);
DELETE FROM part WHERE id IN (2189, 2190, 2191);

INSERT INTO part (id, `TYPE`, `DATA`) VALUES
(2189, 0, '[[26272,-2,-12],[26273,-1,-14],[2955,0,0]]'),
(2190, 1, '[[26274,-10,-7],[26275,-12,-16],[26276,-12,-16],[26277,-5,-12],[26278,-8,-16],[26279,-4,-14],[26280,-6,-13],[26281,-9,-10],[26282,-7,-12],[26283,-6,-12],[26284,-8,-12],[26285,-9,-14],[26286,-2,-15],[26287,-2,-12],[26288,-6,-9],[26289,-10,-11],[2955,0,0]]'),
(2191, 2, '[[26290,-1,-4],[26291,-6,-4],[26292,0,-3],[26293,1,-1],[26294,-1,-4],[26295,-1,-2],[26296,1,-1],[26297,-3,0],[26298,-4,-1],[26299,-2,-4],[26300,-5,-2],[26301,-5,0],[26302,-6,-3],[2955,0,0]]');

INSERT INTO head_avatar (head_id, avatar_id) VALUES
(2189, 26303);

INSERT INTO item_template
(id, `TYPE`, gender, `NAME`, description, level, icon_id, part, is_up_to_up, power_require, gold, gem, head, body, leg)
VALUES
(2080, 5, 3, 'Cải trang Hulk', 'Cải trang thành Hulk', 1, 26272, -1, 0, 0, 0, 0, 2189, 2190, 2191);

DELETE FROM item_default_option WHERE item_template_id IN (2080);

INSERT INTO item_default_option (item_template_id, option_id, param, sort_order) VALUES
(2080, 50, 30, 0),
(2080, 77, 30, 1),
(2080, 103, 30, 2),
(2080, 5, 30, 3),
(2080, 10, 30, 4),
(2080, 80, 50, 5),
(2080, 30, 0, 6);

INSERT INTO item_shop
(tab_id, temp_id, is_new, is_sell, type_sell, cost, icon_spec, option_mode, create_time)
SELECT 1120, 2080, 1, 1, 1, 2000, 0, 0, NOW()
WHERE EXISTS (SELECT 1 FROM tab_shop WHERE id = 1120 AND shop_id = 112)
  AND NOT EXISTS (SELECT 1 FROM item_shop WHERE tab_id = 1120 AND temp_id = 2080);

COMMIT;
