-- Install Marvel/hero costumes generated by costume-tools/build_marvel_costumes.py
SET NAMES utf8mb4;
START TRANSACTION;

DELETE FROM item_shop_option WHERE item_shop_id IN (SELECT id FROM item_shop WHERE tab_id = 1120 AND temp_id IN (2078));
DELETE FROM item_shop WHERE tab_id = 1120 AND temp_id IN (2078);
DELETE FROM item_default_option WHERE item_template_id IN (2078);
DELETE FROM head_avatar WHERE head_id IN (2183, 2184, 2185);
DELETE FROM item_template WHERE id IN (2078);
DELETE FROM part WHERE id IN (2183, 2184, 2185);

INSERT INTO part (id, `TYPE`, `DATA`) VALUES
(2183, 0, '[[26208,1,-15],[26209,-1,-14],[2955,0,0]]'),
(2184, 1, '[[26210,-5,-10],[26211,-9,-21],[26212,-4,-12],[26213,-8,-15],[26214,-9,-14],[26215,-5,-12],[26216,-5,-15],[26217,-8,-11],[26218,-2,-13],[26219,-2,-13],[26220,-2,-12],[26221,-7,-13],[26222,-4,-12],[26223,-5,-10],[26224,-1,-13],[26225,-7,-11],[2955,0,0]]'),
(2185, 2, '[[26226,4,-3],[26227,-3,-5],[26228,2,0],[26229,1,-2],[26230,-1,-1],[26231,-1,1],[26232,2,-1],[26233,-1,-1],[26234,-1,-3],[26235,-2,-3],[26236,-4,-2],[26237,-3,1],[26238,-3,-3],[2955,0,0]]');

INSERT INTO head_avatar (head_id, avatar_id) VALUES
(2183, 26239);

INSERT INTO item_template
(id, `TYPE`, gender, `NAME`, description, level, icon_id, part, is_up_to_up, power_require, gold, gem, head, body, leg)
VALUES
(2078, 5, 3, 'Cải trang Captain America', 'Cải trang thành Captain America', 1, 26208, -1, 0, 0, 0, 0, 2183, 2184, 2185);

DELETE FROM item_default_option WHERE item_template_id IN (2078);

INSERT INTO item_default_option (item_template_id, option_id, param, sort_order) VALUES
(2078, 50, 27, 0),
(2078, 77, 28, 1),
(2078, 103, 22, 2),
(2078, 5, 20, 3),
(2078, 94, 15, 4),
(2078, 30, 0, 5);

INSERT INTO item_shop
(tab_id, temp_id, is_new, is_sell, type_sell, cost, icon_spec, option_mode, create_time)
SELECT 1120, 2078, 1, 1, 1, 2000, 0, 0, NOW()
WHERE EXISTS (SELECT 1 FROM tab_shop WHERE id = 1120 AND shop_id = 112)
  AND NOT EXISTS (SELECT 1 FROM item_shop WHERE tab_id = 1120 AND temp_id = 2078);

COMMIT;
