-- Install Marvel/hero costumes generated by costume-tools/build_marvel_costumes.py
SET NAMES utf8mb4;
START TRANSACTION;

DELETE FROM item_shop_option WHERE item_shop_id IN (SELECT id FROM item_shop WHERE tab_id = 1120 AND temp_id IN (2081));
DELETE FROM item_shop WHERE tab_id = 1120 AND temp_id IN (2081);
DELETE FROM item_default_option WHERE item_template_id IN (2081);
DELETE FROM head_avatar WHERE head_id IN (2192, 2193, 2194);
DELETE FROM item_template WHERE id IN (2081);
DELETE FROM part WHERE id IN (2192, 2193, 2194);

INSERT INTO part (id, `TYPE`, `DATA`) VALUES
(2192, 0, '[[26304,-4,-9],[26305,-2,-7],[2955,0,0]]'),
(2193, 1, '[[26307,-3,-6],[26306,2,-1],[26308,-1,-4],[26309,6,-4],[26310,4,-4],[26311,6,-3],[26312,5,-4],[26313,-3,-10],[26314,-9,-5],[26315,-3,-6],[26316,3,-3],[26317,0,-2],[26318,1,-3],[26319,0,-4],[26320,1,-3],[26321,2,-4],[2955,0,0]]'),
(2194, 2, '[[26323,-2,-3],[26322,-1,-1],[26324,-1,-2],[26325,7,0],[26326,-3,-2],[26327,3,0],[26328,1,-1],[26329,0,1],[26330,-10,-1],[26331,-2,-3],[26332,-4,1],[26333,-7,0],[26334,-4,2],[26335,-4,2]]');

INSERT INTO head_avatar (head_id, avatar_id) VALUES
(2192, 26336);

INSERT INTO item_template
(id, `TYPE`, gender, `NAME`, description, level, icon_id, part, is_up_to_up, power_require, gold, gem, head, body, leg)
VALUES
(2081, 5, 3, 'Cải trang Iron Man', 'Cải trang thành Iron Man', 1, 26304, -1, 0, 0, 0, 0, 2192, 2193, 2194);

DELETE FROM item_default_option WHERE item_template_id IN (2081);

INSERT INTO item_default_option (item_template_id, option_id, param, sort_order) VALUES
(2081, 50, 30, 0),
(2081, 77, 28, 1),
(2081, 103, 28, 2),
(2081, 5, 25, 3),
(2081, 10, 25, 4),
(2081, 18, 100, 5),
(2081, 30, 0, 6);

INSERT INTO item_shop
(tab_id, temp_id, is_new, is_sell, type_sell, cost, icon_spec, option_mode, create_time)
SELECT 1120, 2081, 1, 1, 1, 2000, 0, 0, NOW()
WHERE EXISTS (SELECT 1 FROM tab_shop WHERE id = 1120 AND shop_id = 112)
  AND NOT EXISTS (SELECT 1 FROM item_shop WHERE tab_id = 1120 AND temp_id = 2081);

COMMIT;
