-- Roll back Marvel/hero costumes generated by costume-tools/build_marvel_costumes.py
SET NAMES utf8mb4;
START TRANSACTION;

DELETE FROM item_shop_option WHERE item_shop_id IN (SELECT id FROM item_shop WHERE tab_id = 1120 AND temp_id IN (2081));
DELETE FROM item_shop WHERE tab_id = 1120 AND temp_id IN (2081);
DELETE FROM item_default_option WHERE item_template_id IN (2081);
DELETE FROM head_avatar WHERE head_id IN (2192, 2193, 2194);
DELETE FROM item_template WHERE id IN (2081);
DELETE FROM part WHERE id IN (2192, 2193, 2194);

COMMIT;
