-- Install Marvel/hero costumes generated by costume-tools/build_marvel_costumes.py
SET NAMES utf8mb4;
START TRANSACTION;

DELETE FROM item_shop_option WHERE item_shop_id IN (SELECT id FROM item_shop WHERE tab_id = 1120 AND temp_id IN (2082));
DELETE FROM item_shop WHERE tab_id = 1120 AND temp_id IN (2082);
DELETE FROM item_default_option WHERE item_template_id IN (2082);
DELETE FROM head_avatar WHERE head_id IN (2195, 2196, 2197);
DELETE FROM item_template WHERE id IN (2082);
DELETE FROM part WHERE id IN (2195, 2196, 2197);

INSERT INTO part (id, `TYPE`, `DATA`) VALUES
(2195, 0, '[[26337,4,-5],[26338,5,-3],[2955,0,0]]'),
(2196, 1, '[[26339,4,1],[26340,0,-4],[26341,6,-2],[26342,4,-1],[26343,7,0],[26344,10,1],[26345,8,0],[26346,1,-2],[26347,1,-1],[26348,0,-2],[26349,6,0],[26350,3,0],[26351,3,1],[26352,5,0],[26353,3,-2],[26354,6,-2],[2955,0,0]]'),
(2197, 2, '[[26355,4,-4],[26356,1,-2],[26357,8,1],[26358,5,1],[26359,4,2],[26360,6,2],[26361,7,1],[26362,3,0],[26363,1,1],[26364,4,-1],[26365,-1,3],[26366,-2,4],[26367,-3,2],[2955,0,0]]');

INSERT INTO head_avatar (head_id, avatar_id) VALUES
(2195, 26368);

INSERT INTO item_template
(id, `TYPE`, gender, `NAME`, description, level, icon_id, part, is_up_to_up, power_require, gold, gem, head, body, leg)
VALUES
(2082, 5, 3, 'Cải trang Gojo', 'Cải trang thành Gojo', 1, 26337, -1, 0, 0, 0, 0, 2195, 2196, 2197);

DELETE FROM item_default_option WHERE item_template_id IN (2082);

INSERT INTO item_default_option (item_template_id, option_id, param, sort_order) VALUES
(2082, 50, 30, 0),
(2082, 77, 30, 1),
(2082, 103, 30, 2),
(2082, 5, 30, 3),
(2082, 10, 30, 4),
(2082, 108, 20, 5),
(2082, 30, 0, 6);

INSERT INTO item_shop
(tab_id, temp_id, is_new, is_sell, type_sell, cost, icon_spec, option_mode, create_time)
SELECT 1120, 2082, 1, 1, 1, 2000, 0, 0, NOW()
WHERE EXISTS (SELECT 1 FROM tab_shop WHERE id = 1120 AND shop_id = 112)
  AND NOT EXISTS (SELECT 1 FROM item_shop WHERE tab_id = 1120 AND temp_id = 2082);

COMMIT;
