-- Roll back Marvel/hero costumes generated by costume-tools/build_marvel_costumes.py
SET NAMES utf8mb4;
START TRANSACTION;

DELETE FROM item_shop_option WHERE item_shop_id IN (SELECT id FROM item_shop WHERE tab_id = 1120 AND temp_id IN (2077, 2078, 2079, 2080, 2081, 2082));
DELETE FROM item_shop WHERE tab_id = 1120 AND temp_id IN (2077, 2078, 2079, 2080, 2081, 2082);
DELETE FROM item_default_option WHERE item_template_id IN (2077, 2078, 2079, 2080, 2081, 2082);
DELETE FROM head_avatar WHERE head_id IN (2180, 2181, 2182, 2183, 2184, 2185, 2186, 2187, 2188, 2189, 2190, 2191, 2192, 2193, 2194, 2195, 2196, 2197);
DELETE FROM item_template WHERE id IN (2077, 2078, 2079, 2080, 2081, 2082);
DELETE FROM part WHERE id IN (2180, 2181, 2182, 2183, 2184, 2185, 2186, 2187, 2188, 2189, 2190, 2191, 2192, 2193, 2194, 2195, 2196, 2197);

COMMIT;
