-- Install Marvel/hero costumes generated by costume-tools/build_marvel_costumes.py
SET NAMES utf8mb4;
START TRANSACTION;

DELETE FROM item_shop_option WHERE item_shop_id IN (SELECT id FROM item_shop WHERE tab_id = 1120 AND temp_id IN (2077));
DELETE FROM item_shop WHERE tab_id = 1120 AND temp_id IN (2077);
DELETE FROM item_default_option WHERE item_template_id IN (2077);
DELETE FROM head_avatar WHERE head_id IN (2180, 2181, 2182);
DELETE FROM item_template WHERE id IN (2077);
DELETE FROM part WHERE id IN (2180, 2181, 2182);

INSERT INTO part (id, `TYPE`, `DATA`) VALUES
(2180, 0, '[[26175,-4,-9],[26176,-2,-7],[2955,0,0]]'),
(2181, 1, '[[26178,-3,-6],[26177,2,-1],[26179,-1,-4],[26180,6,-4],[26181,4,-4],[26182,6,-3],[26183,5,-4],[26184,-3,-10],[26185,-9,-5],[26186,-3,-6],[26187,3,-3],[26188,0,-2],[26189,1,-3],[26190,0,-4],[26191,1,-3],[26192,2,-4],[2955,0,0]]'),
(2182, 2, '[[26194,-2,-3],[26193,-1,-1],[26195,-1,-2],[26196,7,0],[26197,-3,-2],[26198,3,0],[26199,1,-1],[26200,0,1],[26201,-10,-1],[26202,-2,-3],[26203,-4,1],[26204,-7,0],[26205,-4,2],[26206,-4,2]]');

INSERT INTO head_avatar (head_id, avatar_id) VALUES
(2180, 26207);

INSERT INTO item_template
(id, `TYPE`, gender, `NAME`, description, level, icon_id, part, is_up_to_up, power_require, gold, gem, head, body, leg)
VALUES
(2077, 5, 3, 'Cải trang Black Parten', 'Cải trang thành Black Parten', 1, 26175, -1, 0, 0, 0, 0, 2180, 2181, 2182);

DELETE FROM item_default_option WHERE item_template_id IN (2077);

INSERT INTO item_default_option (item_template_id, option_id, param, sort_order) VALUES
(2077, 50, 28, 0),
(2077, 77, 28, 1),
(2077, 103, 28, 2),
(2077, 14, 20, 3),
(2077, 97, 20, 4),
(2077, 30, 0, 5);

INSERT INTO item_shop
(tab_id, temp_id, is_new, is_sell, type_sell, cost, icon_spec, option_mode, create_time)
SELECT 1120, 2077, 1, 1, 1, 2000, 0, 0, NOW()
WHERE EXISTS (SELECT 1 FROM tab_shop WHERE id = 1120 AND shop_id = 112)
  AND NOT EXISTS (SELECT 1 FROM item_shop WHERE tab_id = 1120 AND temp_id = 2077);

COMMIT;
