-- Install Marvel/hero costumes generated by costume-tools/build_marvel_costumes.py
SET NAMES utf8mb4;
START TRANSACTION;

DELETE FROM item_shop_option WHERE item_shop_id IN (SELECT id FROM item_shop WHERE tab_id = 1120 AND temp_id IN (2079));
DELETE FROM item_shop WHERE tab_id = 1120 AND temp_id IN (2079);
DELETE FROM item_default_option WHERE item_template_id IN (2079);
DELETE FROM head_avatar WHERE head_id IN (2186, 2187, 2188);
DELETE FROM item_template WHERE id IN (2079);
DELETE FROM part WHERE id IN (2186, 2187, 2188);

INSERT INTO part (id, `TYPE`, `DATA`) VALUES
(2186, 0, '[[26240,-2,-14],[26241,1,-11],[2955,0,0]]'),
(2187, 1, '[[26242,-6,-14],[26243,-12,-17],[26244,-6,-11],[26245,-4,-12],[26246,-7,-10],[26247,-1,-12],[26248,-4,-12],[26249,-12,-11],[26250,-7,-12],[26251,-5,-13],[26252,-1,-10],[26253,-7,-13],[26254,-3,-8],[26255,-3,-7],[26256,-4,-8],[26257,-6,-8],[2955,0,0]]'),
(2188, 2, '[[26258,-3,-6],[26259,-7,-4],[26260,1,-1],[26261,1,-1],[26262,0,0],[26263,-2,0],[26264,2,-1],[26265,-4,-3],[26266,-6,-3],[26267,-1,-3],[26268,-5,-4],[26269,-5,-1],[26270,-6,-3],[2955,0,0]]');

INSERT INTO head_avatar (head_id, avatar_id) VALUES
(2186, 26271);

INSERT INTO item_template
(id, `TYPE`, gender, `NAME`, description, level, icon_id, part, is_up_to_up, power_require, gold, gem, head, body, leg)
VALUES
(2079, 5, 3, 'Cải trang Spider Man', 'Cải trang thành Spider Man', 1, 26240, -1, 0, 0, 0, 0, 2186, 2187, 2188);

DELETE FROM item_default_option WHERE item_template_id IN (2079);

INSERT INTO item_default_option (item_template_id, option_id, param, sort_order) VALUES
(2079, 50, 27, 0),
(2079, 77, 27, 1),
(2079, 103, 27, 2),
(2079, 14, 20, 3),
(2079, 108, 20, 4),
(2079, 30, 0, 5);

INSERT INTO item_shop
(tab_id, temp_id, is_new, is_sell, type_sell, cost, icon_spec, option_mode, create_time)
SELECT 1120, 2079, 1, 1, 1, 2000, 0, 0, NOW()
WHERE EXISTS (SELECT 1 FROM tab_shop WHERE id = 1120 AND shop_id = 112)
  AND NOT EXISTS (SELECT 1 FROM item_shop WHERE tab_id = 1120 AND temp_id = 2079);

COMMIT;
